import { OrderStatus } from '@/types/orders';
import type { ReturnOrder } from '../types';

const NOW = '2026-04-23T10:00:00.000Z';
const CREATED = '2026-04-20T09:00:00.000Z';

export const MOCK_RETURN_ORDERS: ReturnOrder[] = [
  {
    id: 10234,
    code: 'OR-10234',
    status: OrderStatus.SHIPPING,
    totalCost: 450,
    governorate: 'القاهرة',
    city: 'مدينة نصر',
    address: '12 شارع مكرم عبيد',
    customers: {
      id: 2034,
      name: 'أحمد محمد السيد',
      phone_numbers: ['01012345678'],
      governorate: 'القاهرة',
      city: 'مدينة نصر',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10235,
    code: 'OR-10235',
    status: OrderStatus.SHIPPING,
    totalCost: 320,
    governorate: 'الإسكندرية',
    customers: {
      id: 2035,
      name: 'فاطمة علي حسن',
      phone_numbers: ['01123456789'],
      governorate: 'الإسكندرية',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10236,
    code: 'OR-10236',
    status: OrderStatus.SHIPPING,
    totalCost: 780,
    governorate: 'الجيزة',
    customers: {
      id: 2036,
      name: 'محمود إبراهيم',
      phone_numbers: ['01234567890'],
      governorate: 'الجيزة',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10237,
    code: 'OR-10237',
    status: OrderStatus.SHIPPING,
    totalCost: 590,
    governorate: 'القاهرة',
    customers: {
      id: 2037,
      name: 'سارة أحمد',
      phone_numbers: ['01098765432'],
      governorate: 'القاهرة',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10238,
    code: 'OR-10238',
    status: OrderStatus.SHIPPING,
    totalCost: 210,
    governorate: 'الدقهلية',
    customers: {
      id: 2038,
      name: 'خالد عبدالله',
      phone_numbers: ['01187654321'],
      governorate: 'الدقهلية',
      city: 'المنصورة',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10239,
    code: 'OR-10239',
    status: OrderStatus.SHIPPING,
    totalCost: 640,
    governorate: 'الغربية',
    customers: {
      id: 2039,
      name: 'منى حسن',
      phone_numbers: ['01276543210'],
      governorate: 'الغربية',
      city: 'طنطا',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10240,
    code: 'OR-10240',
    status: OrderStatus.SHIPPING,
    totalCost: 820,
    governorate: 'الإسكندرية',
    customers: {
      id: 2040,
      name: 'يوسف مصطفى',
      phone_numbers: ['01065432109'],
      governorate: 'الإسكندرية',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10241,
    code: 'OR-10241',
    status: OrderStatus.SHIPPING,
    totalCost: 390,
    governorate: 'القاهرة',
    customers: {
      id: 2041,
      name: 'نورا سعيد',
      phone_numbers: ['01154321098'],
      governorate: 'القاهرة',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10242,
    code: 'OR-10242',
    status: OrderStatus.SHIPPING,
    totalCost: 1250,
    governorate: 'الجيزة',
    customers: {
      id: 2042,
      name: 'عمر طارق',
      phone_numbers: ['01243210987'],
      governorate: 'الجيزة',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10243,
    code: 'OR-10243',
    status: OrderStatus.SHIPPING,
    totalCost: 475,
    governorate: 'القاهرة',
    customers: {
      id: 2043,
      name: 'هبة كمال',
      phone_numbers: ['01032109876'],
      governorate: 'القاهرة',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10244,
    code: 'OR-10244',
    status: OrderStatus.SHIPPING,
    totalCost: 360,
    governorate: 'أسوان',
    customers: {
      id: 2044,
      name: 'طارق محسن',
      phone_numbers: ['01121098765'],
      governorate: 'أسوان',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
  {
    id: 10245,
    code: 'OR-10245',
    status: OrderStatus.FINAL_RETURN,
    totalCost: 910,
    governorate: 'الإسكندرية',
    customers: {
      id: 2045,
      name: 'ريم أسامة',
      phone_numbers: ['01210987654'],
      governorate: 'الإسكندرية',
    },
    createdAt: CREATED,
    updatedAt: NOW,
  },
];
