import { Receipt } from '../types';

export const MOCK_RECEIPTS: Receipt[] = [
  {
    id: 1,
    invoiceNumber: 'INV-2024-001',
    companyName: 'شركة المصرية للدجية',
    itemsCount: 5,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-28T10:30:00Z',
    totalAmount: 20000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 2,
    invoiceNumber: 'INV-2024-002',
    companyName: 'شركة النيل للتوريدات',
    itemsCount: 3,
    employeeName: 'محمد علي',
    createdAt: '2026-02-27T14:00:00Z',
    totalAmount: 15000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 3,
    invoiceNumber: 'INV-2024-003',
    companyName: 'مصنع الاهرام للبلاستيك',
    itemsCount: 8,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-26T09:15:00Z',
    totalAmount: 35000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 4,
    invoiceNumber: 'INV-2024-004',
    companyName: 'شركة المصرية للدجية',
    itemsCount: 2,
    employeeName: 'احمد محمود',
    createdAt: '2026-02-25T11:45:00Z',
    totalAmount: 8500,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 5,
    invoiceNumber: 'INV-2024-005',
    companyName: 'شركة الدلتا للاغذية',
    itemsCount: 10,
    employeeName: 'محمد علي',
    createdAt: '2026-02-24T16:20:00Z',
    totalAmount: 42000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 6,
    invoiceNumber: 'INV-2024-006',
    companyName: 'مؤسسة الشرق للتجارة',
    itemsCount: 4,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-23T08:00:00Z',
    totalAmount: 12000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 7,
    invoiceNumber: 'INV-2024-007',
    companyName: 'شركة النيل للتوريدات',
    itemsCount: 6,
    employeeName: 'احمد محمود',
    createdAt: '2026-02-22T13:30:00Z',
    totalAmount: 27500,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 8,
    invoiceNumber: 'INV-2024-008',
    companyName: 'شركة المصرية للدجية',
    itemsCount: 7,
    employeeName: 'محمد علي',
    createdAt: '2026-02-21T10:00:00Z',
    totalAmount: 31000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 9,
    invoiceNumber: 'INV-2024-009',
    companyName: 'مصنع الاهرام للبلاستيك',
    itemsCount: 1,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-20T15:45:00Z',
    totalAmount: 5000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 10,
    invoiceNumber: 'INV-2024-010',
    companyName: 'شركة الدلتا للاغذية',
    itemsCount: 9,
    employeeName: 'احمد محمود',
    createdAt: '2026-02-19T09:30:00Z',
    totalAmount: 38000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 11,
    invoiceNumber: 'INV-2024-011',
    companyName: 'مؤسسة الشرق للتجارة',
    itemsCount: 3,
    employeeName: 'محمد علي',
    createdAt: '2026-02-18T12:00:00Z',
    totalAmount: 14500,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 12,
    invoiceNumber: 'INV-2024-012',
    companyName: 'شركة النيل للتوريدات',
    itemsCount: 5,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-17T17:15:00Z',
    totalAmount: 22000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 13,
    invoiceNumber: 'INV-2024-013',
    companyName: 'شركة المصرية للدجية',
    itemsCount: 4,
    employeeName: 'احمد محمود',
    createdAt: '2026-02-16T08:30:00Z',
    totalAmount: 16000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 14,
    invoiceNumber: 'INV-2024-014',
    companyName: 'مصنع الاهرام للبلاستيك',
    itemsCount: 6,
    employeeName: 'محمد علي',
    createdAt: '2026-02-15T14:45:00Z',
    totalAmount: 29000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 15,
    invoiceNumber: 'INV-2024-015',
    companyName: 'شركة الدلتا للاغذية',
    itemsCount: 2,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-14T11:00:00Z',
    totalAmount: 9500,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 16,
    invoiceNumber: 'INV-2024-016',
    companyName: 'مؤسسة الشرق للتجارة',
    itemsCount: 8,
    employeeName: 'احمد محمود',
    createdAt: '2026-02-13T16:30:00Z',
    totalAmount: 33000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 17,
    invoiceNumber: 'INV-2024-017',
    companyName: 'شركة النيل للتوريدات',
    itemsCount: 3,
    employeeName: 'محمد علي',
    createdAt: '2026-02-12T09:00:00Z',
    totalAmount: 11500,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 18,
    invoiceNumber: 'INV-2024-018',
    companyName: 'شركة المصرية للدجية',
    itemsCount: 7,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-11T13:15:00Z',
    totalAmount: 26000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 19,
    invoiceNumber: 'INV-2024-019',
    companyName: 'مصنع الاهرام للبلاستيك',
    itemsCount: 5,
    employeeName: 'احمد محمود',
    createdAt: '2026-02-10T10:45:00Z',
    totalAmount: 19000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 20,
    invoiceNumber: 'INV-2024-020',
    companyName: 'شركة الدلتا للاغذية',
    itemsCount: 4,
    employeeName: 'محمد علي',
    createdAt: '2026-02-09T15:30:00Z',
    totalAmount: 17500,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 21,
    invoiceNumber: 'INV-2024-021',
    companyName: 'مؤسسة الشرق للتجارة',
    itemsCount: 6,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-08T08:15:00Z',
    totalAmount: 24000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 22,
    invoiceNumber: 'INV-2024-022',
    companyName: 'شركة النيل للتوريدات',
    itemsCount: 2,
    employeeName: 'احمد محمود',
    createdAt: '2026-02-07T12:00:00Z',
    totalAmount: 7500,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
  {
    id: 23,
    invoiceNumber: 'INV-2024-023',
    companyName: 'شركة المصرية للدجية',
    itemsCount: 9,
    employeeName: 'محمد علي',
    createdAt: '2026-02-06T14:30:00Z',
    totalAmount: 41000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير مقبولة',
  },
  {
    id: 24,
    invoiceNumber: 'INV-2024-024',
    companyName: 'مصنع الاهرام للبلاستيك',
    itemsCount: 3,
    employeeName: 'سارة احمد',
    createdAt: '2026-02-05T09:45:00Z',
    totalAmount: 13000,
    transactionType: 'مشتريات',
    acceptanceStatus: 'فواتير غير مقبولة',
  },
];

export const DEFAULT_PAGE_SIZE = 10;

export const MOCK_SUPPLIER_OPTIONS = [
  { key: 'شركة المصرية للدجية', value: 'شركة المصرية للدجية' },
  { key: 'شركة النيل للتوريدات', value: 'شركة النيل للتوريدات' },
  { key: 'مصنع الاهرام للبلاستيك', value: 'مصنع الاهرام للبلاستيك' },
  { key: 'شركة الدلتا للاغذية', value: 'شركة الدلتا للاغذية' },
  { key: 'مؤسسة الشرق للتجارة', value: 'مؤسسة الشرق للتجارة' },
];

export const MOCK_EMPLOYEE_OPTIONS = [
  { key: 'سارة احمد', value: 'سارة احمد' },
  { key: 'محمد علي', value: 'محمد علي' },
  { key: 'احمد محمود', value: 'احمد محمود' },
];
