export const ORDER_STATUS_ARABIC_LABELS: Record<string, string> = {
  NEW_ORDER: 'طلب جديد',
  ATTEMPTED: 'تمت المحاولة',
  WAITING_FOR_PAYMENT: 'بانتظار الدفع',
  WHATSAPP: 'واتساب',
  WHATSAPP_CONFIRMED: 'واتساب مؤكد',
  EDIT_REJECTED: 'رفض التعديل',
  POSTPONED: 'مؤجل',
  CALL_AGAIN: 'اعادة اتصال',
  STOPPED: 'متوقف',
  CANCELLED: 'ملغى',
  UNCOMPLETED: 'غير مكتمل',
  CONFIRMED: 'مؤكد',
  WAITING_FOR_PACKAGING: 'في انتظار التغليف',
  PREPARED: 'جاري التجهيز',
  WAITING_FOR_APPROVAL: 'في انتظار الموافقة',
  SHIPPING: 'شحن',
  RETURNED_DELIVERED: 'مرتجع بعد التسليم',
  DELIVERED: 'تم التسليم',
  PARTIAL_DELIVERY: 'تسليم جزئي',
  MISSING: 'مفقود',
};

export const ORDER_STATUS_CHART_COLORS: Record<string, string> = {
  NEW_ORDER: '#3b82f6',
  ATTEMPTED: '#8b5cf6',
  WAITING_FOR_PAYMENT: '#f59e0b',
  WHATSAPP: '#22c55e',
  WHATSAPP_CONFIRMED: '#16a34a',
  EDIT_REJECTED: '#0097a7',
  POSTPONED: '#6366f1',
  CALL_AGAIN: '#14b8a6',
  STOPPED: '#9ca3af',
  CANCELLED: '#ef4444',
  UNCOMPLETED: '#f97316',
  CONFIRMED: '#10b981',
  WAITING_FOR_PACKAGING: '#ff9800',
  PREPARED: '#7c3aed',
  WAITING_FOR_APPROVAL: '#ff9800',
  SHIPPING: '#06b6d4',
  RETURNED_DELIVERED: '#ec4899',
  DELIVERED: '#059669',
  PARTIAL_DELIVERY: '#d97706',
  MISSING: '#dc2626',
};
