// Areas organized by governorate
export const AREAS_BY_GOVERNORATE: Record<string, { key: string; value: string }[]> = {
  cairo: [
    { key: 'nasr_city', value: 'مدينة نصر' },
    { key: 'heliopolis', value: 'مصر الجديدة' },
    { key: 'maadi', value: 'المعادي' },
    { key: 'zamalek', value: 'الزمالك' },
    { key: 'downtown', value: 'وسط البلد' },
    { key: 'new_cairo', value: 'القاهرة الجديدة' },
    { key: '6_october_cairo', value: '6 أكتوبر' },
    { key: 'shoubra', value: 'شبرا' },
    { key: 'abbassia', value: 'عباسية' },
    { key: 'hadayek_el_qobba', value: 'حدائق القبة' },
    { key: 'rod_el_farag', value: 'روض الفرج' },
    { key: 'ain_shams', value: 'عين شمس' },
    { key: 'manshiet_nasser', value: 'منشية ناصر' },
  ],
  giza: [
    { key: 'dokki', value: 'الدقي' },
    { key: 'zamalek_giza', value: 'الزمالك' },
    { key: 'agouza', value: 'العجوزة' },
    { key: 'faisal', value: 'فيصل' },
    { key: 'haram', value: 'الهرم' },
    { key: '6_october', value: '6 أكتوبر' },
    { key: 'sheikh_zayed', value: 'الشيخ زايد' },
    { key: 'new_giza', value: 'نيو جيزة' },
    { key: 'giza_center', value: 'وسط الجيزة' },
    { key: 'imbaba', value: 'إمبابة' },
    { key: 'bulaq_el_dakrour', value: 'بولاق الدكرور' },
    { key: 'warraq', value: 'الوراق' },
  ],
  alexandria: [
    { key: 'alex_center', value: 'وسط الإسكندرية' },
    { key: 'sidi_bishr', value: 'سيدي بشر' },
    { key: 'stanley', value: 'ستانلي' },
    { key: 'gleem', value: 'جليم' },
    { key: 'sidi_gaber', value: 'سيدي جابر' },
    { key: 'smouha', value: 'سموحة' },
    { key: 'louran', value: 'لوران' },
    { key: 'montaza', value: 'المنتزه' },
    { key: 'miami', value: 'ميامي' },
    { key: 'agamy', value: 'العجمي' },
    { key: 'borg_el_arab', value: 'برج العرب' },
    { key: 'ras_el_tin', value: 'رأس التين' },
  ],
  dakahlia: [
    { key: 'mansoura', value: 'المنصورة' },
    { key: 'talkha', value: 'طلخة' },
    { key: 'mit_ghamr', value: 'ميت غمر' },
    { key: 'belqas', value: 'بلقاس' },
    { key: 'dikirnis', value: 'دكرنس' },
    { key: 'aqeed', value: 'عقيد' },
    { key: 'mansoura_center', value: 'وسط المنصورة' },
  ],
  red_sea: [
    { key: 'hurghada', value: 'الغردقة' },
    { key: 'safaga', value: 'سفاجا' },
    { key: 'el_gouna', value: 'الجونة' },
    { key: 'marsa_alam', value: 'مرسى علم' },
    { key: 'ras_ghareb', value: 'رأس غارب' },
  ],
  beheira: [
    { key: 'damanhur', value: 'دمنهور' },
    { key: 'kafr_el_dawar', value: 'كفر الدوار' },
    { key: 'rosetta', value: 'رشيد' },
    { key: 'abu_homos', value: 'أبو حمص' },
    { key: 'idku', value: 'إدكو' },
    { key: 'shubrakhit', value: 'شبراخيت' },
  ],
  fayoum: [
    { key: 'fayoum_center', value: 'وسط الفيوم' },
    { key: 'tamia', value: 'طامية' },
    { key: 'sinnuris', value: 'سنورس' },
    { key: 'itsa', value: 'إطسا' },
    { key: 'absweg', value: 'أبشواي' },
  ],
  gharbia: [
    { key: 'tanta', value: 'طنطا' },
    { key: 'mahalla_kubra', value: 'المحلة الكبرى' },
    { key: 'zefta', value: 'زفتى' },
    { key: 'kafr_el_zayat', value: 'كفر الزيات' },
    { key: 'samanoud', value: 'سمنود' },
    { key: 'basioun', value: 'بسيون' },
  ],
  ismailia: [
    { key: 'ismailia_center', value: 'وسط الإسماعيلية' },
    { key: 'fayed', value: 'فايد' },
    { key: 'qantara_sharq', value: 'القنطرة شرق' },
    { key: 'qantara_gharb', value: 'القنطرة غرب' },
    { key: 'abou_sweir', value: 'أبو صوير' },
  ],
  menofia: [
    { key: 'shibin_el_kom', value: 'شبين الكوم' },
    { key: 'tala', value: 'تلا' },
    { key: 'ashmun', value: 'أشمون' },
    { key: 'beraig', value: 'بركة السبع' },
    { key: 'menouf', value: 'منوف' },
  ],
  minya: [
    { key: 'minya_center', value: 'وسط المنيا' },
    { key: 'mallawi', value: 'ملوي' },
    { key: 'deir_mawas', value: 'دير مواس' },
    { key: 'maghagha', value: 'مغاغة' },
    { key: 'beni_mazar', value: 'بني مزار' },
  ],
  qalyubia: [
    { key: 'banha', value: 'بنها' },
    { key: 'shubra_el_kheima', value: 'شبرا الخيمة' },
    { key: 'qalyub', value: 'قليوب' },
    { key: 'toukh', value: 'طوخ' },
    { key: 'kafr_shukr', value: 'كفر شكر' },
  ],
  new_valley: [
    { key: 'kharga', value: 'الخارجة' },
    { key: 'dakhla', value: 'الداخلة' },
    { key: 'farafra', value: 'الفرافرة' },
    { key: 'baris', value: 'باريس' },
  ],
  suez: [
    { key: 'suez_center', value: 'وسط السويس' },
    { key: 'port_tawfiq', value: 'بورتوفيق' },
    { key: 'attaka', value: 'عتاقة' },
    { key: 'faisal_suez', value: 'فيصل' },
  ],
  aswan: [
    { key: 'aswan_center', value: 'وسط أسوان' },
    { key: 'kom_ombo', value: 'كوم أمبو' },
    { key: 'edfu', value: 'إدفو' },
    { key: 'nasr_nubia', value: 'ناصر النوبية' },
  ],
  assiut: [
    { key: 'assiut_center', value: 'وسط أسيوط' },
    { key: 'abu_tig', value: 'أبو تيج' },
    { key: 'dayrout', value: 'ديروط' },
    { key: 'qusiya', value: 'قوصية' },
    { key: 'manfalut', value: 'منفلوط' },
  ],
  beni_suef: [
    { key: 'beni_suef_center', value: 'وسط بني سويف' },
    { key: 'al_wasta', value: 'الواسط' },
    { key: 'new_beni_suef', value: 'بني سويف الجديدة' },
    { key: 'beba', value: 'ببا' },
  ],
  port_said: [
    { key: 'port_said_center', value: 'وسط بورسعيد' },
    { key: 'port_fouad', value: 'بورتوف Said' },
    { key: 'al_arab', value: 'العرب' },
  ],
  damietta: [
    { key: 'damietta_center', value: 'وسط دمياط' },
    { key: 'new_damietta', value: 'دمياط الجديدة' },
    { key: 'ras_el_bar', value: 'رأس البر' },
    { key: 'kafr_saad', value: 'كفر سعد' },
  ],
  sharkia: [
    { key: 'zagazig', value: 'الزقازيق' },
    { key: '10th_ramadan', value: '10 رمضان' },
    { key: 'belbeis', value: 'بلبيس' },
    { key: 'hehia', value: 'ههيا' },
    { key: 'abou_hammad', value: 'أبو حماد' },
  ],
  south_sinai: [
    { key: 'sharm_el_sheikh', value: 'شرم الشيخ' },
    { key: 'dahab', value: 'دهب' },
    { key: 'nuweiba', value: 'نويبع' },
    { key: 'tur', value: 'الطور' },
  ],
  kafr_el_sheikh: [
    { key: 'kafr_el_sheikh_center', value: 'وسط كفر الشيخ' },
    { key: 'disuq', value: 'دسوق' },
    { key: 'fuwwah', value: 'فوه' },
    { key: 'sidi_salim', value: 'سيدي سالم' },
  ],
  matrouh: [
    { key: 'marsa_matrouh', value: 'مرسى مطروح' },
    { key: 'el_alamein', value: 'العلمين' },
    { key: 'siwa', value: 'سيوة' },
    { key: 'ras_el_hekma', value: 'رأس الحكمة' },
  ],
  luxor: [
    { key: 'luxor_center', value: 'وسط الأقصر' },
    { key: 'karnak', value: 'الكرنك' },
    { key: 'esna', value: 'إسنا' },
  ],
  qena: [
    { key: 'qena_center', value: 'وسط قنا' },
    { key: 'qus', value: 'قوص' },
    { key: 'naqada', value: 'نقادة' },
    { key: 'dendera', value: 'دندرة' },
  ],
  north_sinai: [
    { key: 'el_arish', value: 'العريش' },
    { key: 'sheikh_zuweid', value: 'الشيخ زويد' },
    { key: 'rafah', value: 'رفح' },
    { key: 'bir_el_abd', value: 'بئر العبد' },
  ],
  sohag: [
    { key: 'sohag_center', value: 'وسط سوهاج' },
    { key: 'akhmeem', value: 'أخميم' },
    { key: 'tema', value: 'طما' },
    { key: 'tahta', value: 'طهطا' },
    { key: 'girga', value: 'جرجا' },
  ],
};

// Helper function to get areas by governorate key
export const getAreasByGovernorate = (governorateKey: string) => {
  return AREAS_BY_GOVERNORATE[governorateKey] || [];
};

