export const GOVERNORATES = [
  { key: 'cairo' as const, value: 'القاهرة' },
  { key: 'giza' as const, value: 'الجيزة' },
  { key: 'alexandria' as const, value: 'الإسكندرية' },
  { key: 'dakahlia' as const, value: 'الدقهلية' },
  { key: 'red_sea' as const, value: 'البحر الأحمر' },
  { key: 'beheira' as const, value: 'البحيرة' },
  { key: 'fayoum' as const, value: 'الفيوم' },
  { key: 'gharbia' as const, value: 'الغربية' },
  { key: 'ismailia' as const, value: 'الإسماعيلية' },
  { key: 'menofia' as const, value: 'المنوفية' },
  { key: 'minya' as const, value: 'المنيا' },
  { key: 'qalyubia' as const, value: 'القليوبية' },
  { key: 'new_valley' as const, value: 'الوادي الجديد' },
  { key: 'suez' as const, value: 'السويس' },
  { key: 'aswan' as const, value: 'أسوان' },
  { key: 'assiut' as const, value: 'أسيوط' },
  { key: 'beni_suef' as const, value: 'بني سويف' },
  { key: 'port_said' as const, value: 'بورسعيد' },
  { key: 'damietta' as const, value: 'دمياط' },
  { key: 'sharkia' as const, value: 'الشرقية' },
  { key: 'south_sinai' as const, value: 'جنوب سيناء' },
  { key: 'kafr_el_sheikh' as const, value: 'كفر الشيخ' },
  { key: 'matrouh' as const, value: 'مطروح' },
  { key: 'luxor' as const, value: 'الأقصر' },
  { key: 'qena' as const, value: 'قنا' },
  { key: 'north_sinai' as const, value: 'شمال سيناء' },
  { key: 'sohag' as const, value: 'سوهاج' },
];
