const ordersTabs = [
  { label: 'جميع الطلبات', count: 3, iconComponent: 'Package' },
  { label: 'طلبات جديده', count: 3, icon: 'CheckCircle' },
  { label: 'في الشحن', count: 200, icon: 'Truck' },
  { label: 'في الشحن', count: 15000, icon: 'Truck' },
  { label: 'في الشحن', count: 30000, icon: 'Truck' },
  { label: 'في الشحن', count: 67, icon: 'Truck' },
  { label: 'في الشحن', count: 1, icon: 'Truck' },
  { label: 'في الشحن', count: 0, icon: 'Truck' },
  { label: 'في الشحن', count: 2, icon: 'Truck' },
];

export const mockProducts = [
  {
    id: 1,
    name: 'Orginal',
    price: '930',
    image: '/modern-coffee-maker.png',
    variants: [
      { id: 1, name: 'أسود المقاسات 42-43' },
      { id: 2, name: 'أسود المقاسات 42-43' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-02T00:00:00.000Z',
  },
  {
    id: 2,
    name: 'Orginal',
    price: '930',
    image: '/modern-coffee-maker.png',
    variants: [
      { id: 1, name: 'أسود المقاسات 42-43' },
      { id: 2, name: 'أسود المقاسات 42-43' },
      { id: 3, name: 'أسود المقاسات 42-43' },
      { id: 4, name: 'أسود المقاسات 42-43' },
    ],
    createdAt: '2024-01-03T00:00:00.000Z',
    updatedAt: '2024-01-04T00:00:00.000Z',
  },
  {
    id: 3,
    name: 'Orginal',
    price: '930',
    image: '/modern-coffee-maker.png',
    variants: [],
    createdAt: '2024-01-05T00:00:00.000Z',
    updatedAt: '2024-01-06T00:00:00.000Z',
  },
  {
    id: 4,
    name: 'Orginal',
    price: '930',
    image: '/modern-coffee-maker.png',
    variants: [],
    createdAt: '2024-01-07T00:00:00.000Z',
    updatedAt: '2024-01-08T00:00:00.000Z',
  },
];

const dummyCards = [
  {
    id: 1,
    name: 'Order 1',
    phone: '0123456789',
    government: 'القاهرة',
    items: ['42 نايك اسود', '43 اديداس ابيض'],
    price: 5000,
    trys: 2,
    status: 'في الشحن',
    city: 'Cairo',
    alert: 3,
  },
  {
    id: 2,
    name: 'Order 2',
    phone: '0223456789',
    government: 'القاهرة',
    items: ['42 نايك اسود', '43 اديداس ابيض'],
    price: 5000,
    trys: 3,
    status: 'في الشحن',
    city: 'sad',
  },
  {
    id: 3,
    name: 'Order 3',
    phone: '0323456789',
    government: 'القاهرة',
    items: ['42 نايك اسود', '43 اديداس ابيض'],
    price: 5000,
    trys: 2,
    status: 'في الشحن',
    city: 'das',
  },
  {
    id: 4,
    name: 'Order 4',
    phone: '0423456789',
    government: 'القاهرة',
    items: ['42 نايك اسود', '43 اديداس ابيض'],
    price: 5000,
    trys: 2,
    status: 'في الشحن',
    city: 'valorant',
  },
  {
    id: 5,
    name: 'Order 5',
    phone: '0523556789',
    government: 'القاهرة',
    items: ['52 نايك اسود', '53 اديداس ابيض'],
    price: 5000,
    trys: 2,
    status: 'في الشحن',
    city: 'valorant',
    alert: 10,
  },
  {
    id: 6,
    name: 'Order 6',
    phone: '0623656789',
    government: 'القاهرة',
    items: ['62 نايك اسود', '63 اديداس ابيض'],
    price: 5000,
    trys: 2,
    status: 'في الشحن',
    city: 'valorant',
  },
  {
    id: 7,
    name: 'أحمد محمد',
    phone: '0723757789',
    government: 'الجيزة',
    items: ['تيشيرت قطني', 'بنطال جينز'],
    price: 3200,
    trys: 2,
    status: 'جديد',
    city: 'المعادي',
  },
  {
    id: 8,
    name: 'فاطمة علي',
    phone: '0823456789',
    government: 'الإسكندرية',
    items: ['حذاء رياضي', 'جاكيت شتوي'],
    price: 7800,
    trys: 3,
    status: 'تم التسليم',
    city: 'الدقي',
  },
  {
    id: 9,
    name: 'محمد حسن',
    phone: '0923456789',
    government: 'القاهرة',
    items: ['قبعة بيسبول', 'حقيبة سفر'],
    price: 4500,
    trys: 2,
    status: 'في الشحن',
    city: 'مدينة نصر',
  },
  {
    id: 10,
    name: 'نور الدين',
    phone: '1023456789',
    government: 'الجيزة',
    items: ['حذاء كعب', 'فستان أنيق'],
    price: 6200,
    trys: 2,
    status: 'جديد',
    city: 'المعادي',
  },
  {
    id: 11,
    name: 'سارة أحمد',
    phone: '1123456789',
    government: 'الإسكندرية',
    items: ['قميص رسمي', 'ربطة عنق'],
    price: 3800,
    trys: 2,
    status: 'في الشحن',
    city: 'الدقي',
  },
  {
    id: 12,
    name: 'علي محمود',
    phone: '1223456789',
    government: 'القاهرة',
    items: ['ساعة يد', 'إكسسوارات ذهبية'],
    price: 12500,
    trys: 1,
    status: 'تم التسليم',
    city: 'مدينة نصر',
  },
  {
    id: 13,
    name: 'مريم سعد',
    phone: '1323456789',
    government: 'الجيزة',
    items: ['نظارة شمسية', 'محفظة جلد'],
    price: 2900,
    trys: 3,
    status: 'جديد',
    city: 'المعادي',
  },
  {
    id: 14,
    name: 'خالد إبراهيم',
    phone: '1423456789',
    government: 'الإسكندرية',
    items: ['عطر فرنسي', 'كريم عناية'],
    price: 8500,
    trys: 2,
    status: 'في الشحن',
    city: 'الدقي',
  },
  {
    id: 15,
    name: 'هند محمد',
    phone: '1523456789',
    government: 'القاهرة',
    items: ['حذاء بوت', 'معطف شتوي'],
    price: 9500,
    trys: 2,
    status: 'جديد',
    city: 'مدينة نصر',
  },
  {
    id: 16,
    name: 'يوسف أحمد',
    phone: '1623456789',
    government: 'الجيزة',
    items: ['حقيبة يد', 'أحذية مريحة'],
    price: 5200,
    trys: 1,
    status: 'تم التسليم',
    city: 'المعادي',
  },
  {
    id: 17,
    name: 'رانيا حسن',
    phone: '1723456789',
    government: 'الإسكندرية',
    items: ['قميص بولو', 'شورت رياضي'],
    price: 4100,
    trys: 3,
    status: 'في الشحن',
    city: 'الدقي',
  },
  {
    id: 18,
    name: 'طارق علي',
    phone: '1823456789',
    government: 'القاهرة',
    items: ['فستان صيفي', 'حذاء مفتوح'],
    price: 6800,
    trys: 2,
    status: 'جديد',
    city: 'مدينة نصر',
  },
  {
    id: 19,
    name: 'دنيا محمود',
    phone: '1923456789',
    government: 'الجيزة',
    items: ['جاكيت جلد', 'قميص كتان'],
    price: 7200,
    trys: 2,
    status: 'في الشحن',
    city: 'المعادي',
  },
  {
    id: 20,
    name: 'عمر سعد',
    phone: '2023456789',
    government: 'الإسكندرية',
    items: ['إكسسوارات فضية', 'سوار ذهبي'],
    price: 9800,
    trys: 1,
    status: 'تم التسليم',
    city: 'الدقي',
  },
];

export { ordersTabs, dummyCards };
