import { Region } from '../types';

export const egyptRegions: Region[] = [
  { name: 'القاهرة', percent: 70, value: 200 },
  { name: 'الجيزة', percent: 60, value: 200 },
  { name: 'القليوبية', percent: 60, value: 200 },
  { name: 'الإسكندرية', percent: 60, value: 200 },
  { name: 'الإسماعيلية', percent: 60, value: 200 },
  { name: 'المنوفية', percent: 70, value: 200 },
  { name: 'الدقهلية', percent: 60, value: 200 },
  { name: 'بورسعيد', percent: 60, value: 200 },
  { name: 'السويس', percent: 60, value: 200 },
  { name: 'قنا', percent: 60, value: 200 },
  { name: 'الغربية', percent: 60, value: 200 },
  { name: 'كفر الشيخ', percent: 60, value: 200 },
  { name: 'البحيرة', percent: 60, value: 200 },
  { name: 'المنيا', percent: 60, value: 200 },
  { name: 'مطروح', percent: 60, value: 200 },
  { name: 'شمال سيناء', percent: 60, value: 200 },
  { name: 'جنوب سيناء', percent: 60, value: 200 },
  { name: 'بني سويف', percent: 60, value: 200 },
  { name: 'الفيوم', percent: 60, value: 200 },
  { name: 'أسيوط', percent: 60, value: 200 },
  { name: 'سوهاج', percent: 60, value: 200 },
  { name: 'الشرقية', percent: 60, value: 200 },
  { name: 'دمياط', percent: 60, value: 200 },
  { name: 'أسوان', percent: 60, value: 200 },
  { name: 'الأقصر', percent: 60, value: 200 },
  { name: 'البحر الأحمر', percent: 60, value: 200 },
  { name: 'الوادي الجديد', percent: 60, value: 200 },
];

