// constants/stores/storesTable.ts

import { IStoreTableHeader } from '../types/stores';

export const STORES_TABLE_HEADERS: IStoreTableHeader[] = [
  { id: 1, key: 'storeName', label: 'اسم المتجر' },
  { id: 2, key: 'requestsCount', label: 'عدد الطلبات' },
  { id: 3, key: 'department', label: 'القسم' },
  { id: 4, key: 'sales', label: 'المبيعات' },
  { id: 5, key: 'revenue', label: 'الايرادات' },
  { id: 6, key: 'deliveryRate', label: 'نسبة التسليم' },
  { id: 7, key: 'dateAdded', label: 'تاريخ الاضافة' },
  { id: 8, key: 'profitDate', label: 'ارباح التاجر' },
  { id: 9, key: 'actions', label: 'اجراءات' },
];

export const STORES_SAMPLE_DATA = [
  {
    id: 1,
    storeName: 'أحذية ماشي',
    requestsCount: 40,
    department: 'أحذية',
    sales: '12,850',
    revenue: '850,300 جنية',
    deliveryRate: '94%',
    dateAdded: 'فبراير 2024',
    profitDate: '850,300 جنية',
    actions: '-',
    status: 'active' as const,
  },
  {
    id: 2,
    storeName: 'حقائب جلدية',
    requestsCount: 40,
    department: 'حقائب',
    sales: '10,200',
    revenue: '420,000 جنية',
    deliveryRate: '87%',
    dateAdded: 'مارس 2024',
    profitDate: '380,000 جنية',
    actions: '-',
    status: 'active' as const,
  },
  {
    id: 3,
    storeName: 'ملابس رياضية',
    requestsCount: 40,
    department: 'ملابس',
    sales: '10,500',
    revenue: '203,000 جنية',
    deliveryRate: '92%',
    dateAdded: 'أبريل 2024',
    profitDate: '380,000 جنية',
    actions: 'Ban',
    status: 'inactive' as const,
  },
  {
    id: 4,
    storeName: 'أحذية ماشي',
    requestsCount: 40,
    department: 'أحذية',
    sales: '12,850',
    revenue: '850,300 جنية',
    deliveryRate: '94%',
    dateAdded: 'فبراير 2024',
    profitDate: '850,300 جنية',
    actions: 'Ban',
    status: 'inactive' as const,
  },
];
