import { SupplierInvoice, SupplierInvoiceItem } from '../types';

export const DEFAULT_PAGE_SIZE = 10;

const MOCK_ITEMS: SupplierInvoiceItem[] = [
  {
    id: 1,
    productName: 'نايك شبشب اسود 40/42',
    productImage: '/placeholder-product.png',
    quantity: 50,
    price: 450.0,
    total: 20000,
  },
  {
    id: 2,
    productName: 'نايك شبشب اسود 40/42',
    productImage: '/placeholder-product.png',
    quantity: 50,
    price: 450.0,
    total: 20000,
  },
  {
    id: 3,
    productName: 'نايك شبشب اسود 40/42',
    productImage: '/placeholder-product.png',
    quantity: 50,
    price: 450.0,
    total: 20000,
  },
];

export const MOCK_SUPPLIER_INVOICES: SupplierInvoice[] = [
  {
    id: 1,
    invoiceNumber: 'INV-2024-001',
    companyName: 'الشركة المصرية للاحذية',
    employeeName: 'موظف مشتريات',
    createdByName: 'محمد احمد',
    itemsCount: 3,
    createdAt: '2026-02-28T10:30:00Z',
    totalAmount: 50000,
    transactionType: 'مشتريات',
    items: MOCK_ITEMS,
  },
  {
    id: 2,
    invoiceNumber: 'INV-2024-002',
    companyName: 'الشركة المصرية للاحذية',
    employeeName: 'موظف مشتريات',
    createdByName: 'سارة احمد',
    itemsCount: 3,
    createdAt: '2026-02-28T14:00:00Z',
    totalAmount: 35000,
    transactionType: 'مشتريات',
    items: MOCK_ITEMS,
  },
  {
    id: 3,
    invoiceNumber: 'INV-2024-003',
    companyName: 'الشركة المصرية للاحذية',
    employeeName: 'موظف مشتريات',
    createdByName: 'سارة احمد',
    itemsCount: 3,
    createdAt: '2026-02-26T09:00:00Z',
    totalAmount: 15000,
    transactionType: 'مشتريات',
    items: MOCK_ITEMS,
  },
  {
    id: 4,
    invoiceNumber: 'INV-2024-004',
    companyName: 'الشركة المصرية للاحذية',
    employeeName: 'موظف مشتريات',
    createdByName: 'سارة احمد',
    itemsCount: 3,
    createdAt: '2026-02-26T11:00:00Z',
    totalAmount: -50000,
    transactionType: 'مدفوع',
    items: MOCK_ITEMS,
  },
  {
    id: 5,
    invoiceNumber: 'INV-2024-005',
    companyName: 'الشركة المصرية للاحذية',
    employeeName: 'موظف مشتريات',
    createdByName: 'سارة احمد',
    itemsCount: 3,
    createdAt: '2026-02-25T08:00:00Z',
    totalAmount: -50000,
    transactionType: 'مرتجعات',
    items: MOCK_ITEMS,
  },
  {
    id: 6,
    invoiceNumber: 'INV-2024-006',
    companyName: 'الشركة المصرية للاحذية',
    employeeName: 'موظف مشتريات',
    createdByName: 'سارة احمد',
    itemsCount: 3,
    createdAt: '2026-02-24T16:00:00Z',
    totalAmount: 60000,
    transactionType: 'مشتريات',
    items: MOCK_ITEMS,
  },
];
