export const TABLE_HEADERS = [
  { id: 1, key: 'name', label: 'الاسم' },
  { id: 2, key: 'performance', label: 'الاداء' },
  { id: 3, key: 'totalCalls', label: 'إجمالي المكالمات' },
  { id: 4, key: 'confirmed', label: 'تأكيد' },
  { id: 5, key: 'cancelled', label: 'إلغاء' },
  { id: 6, key: 'postponed', label: 'تاجيل' },
  { id: 7, key: 'noResponse', label: 'عدم الرد' },
  { id: 8, key: 'incomplete', label: 'غير مكتمل' },
  { id: 9, key: 'workHours', label: 'ساعات العمل' },
  { id: 10, key: 'breakDuration', label: 'مدة التوقف' },
];

export const TABLE_DATA = [
  {
    id: 1,
    name: 'ساره خالد',
    performance: 95,
    totalCalls: '112',
    confirmed: '88',
    cancelled: '10',
    postponed: '14',
    noResponse: '14',
    incomplete: '5',
    workHours: '9 ساعات',
    breakDuration: '40 دقيقة',
  },
  {
    id: 2,
    name: 'ساره خالد',
    performance: 85,
    totalCalls: '112',
    confirmed: '88',
    cancelled: '10',
    postponed: '14',
    noResponse: '14',
    incomplete: '5',
    workHours: '9 ساعات',
    breakDuration: '40 دقيقة',
  },
  {
    id: 3,
    name: 'ساره خالد',
    performance: 84,
    totalCalls: '112',
    confirmed: '88',
    cancelled: '10',
    postponed: '14',
    noResponse: '14',
    incomplete: '5',
    workHours: '9 ساعات',
    breakDuration: '40 دقيقة',
  },
  {
    id: 4,
    name: 'ساره خالد',
    performance: 45,
    totalCalls: '112',
    confirmed: '88',
    cancelled: '10',
    postponed: '14',
    noResponse: '14',
    incomplete: '5',
    workHours: '9 ساعات',
    breakDuration: '40 دقيقة',
  },
  // Add more data objects as needed
];
