import { InvoiceLabels } from '../types/invoice';

export const INVOICE_LABELS: Record<'ar' | 'en', InvoiceLabels> = {
  ar: {
    recipientDetails: 'تفاصيل المستلم',
    phoneNumber: 'رقم الهاتف',
    number1: 'الرقم 1',
    number2: 'الرقم 2',
    address: 'العنوان',
    packagingNotes: 'ملاحظات التعبئة',
    packagingWarning: 'تأكد من أنه غير ممزق وفي حالة جيدة دون عيوب.',
    shipmentContents: 'محتوى الشحنة',
    shippingNotes: 'ملاحظات الشحن',
    shippingInfo: 'معلومات الشحن',
    allowOpenShipment: 'هل يُسمح بفتح الشحنة؟',
    paymentMethod: 'طريقة الدفع',
    paymentStatus: 'حالة الدفع',
    shipmentStatus: 'حالة الشحنة',
    customerSchedule: 'مواعيد العميل',
    totalPrice: 'السعر الإجمالي',
    nonReceiptMessage: 'في حالة عدم الاستلام: سيتم دفع مبلغ',
    productCount: 'عدد المنتجات',
    shippingBarcode: 'Shipping Barcode',
    contactMessage: 'للاستفسارات والشكاوى، يرجى الاتصال بنا.',
    senderName: 'اسم الراسل',
    workNumbers: 'أرقام العمل المتاحة',
    scanToContact: 'امسح الكود للتواصل',
    yes: 'نعم',
    no: 'لا',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    cashOnDelivery: 'الدفع عند الاستلام',
    cod: 'COD',
    delivery: 'توصيل',
    codAmount: 'مبلغ التحصيل',
    nonReceiptCost: 'تكلفة عدم الاستلام',
    merchant: 'التاجر',
    deliverTo: 'توصيل إلى',
    area: 'المنطقة',
    landmark: 'علامة مميزة',
    openShipment: 'فتح الشحنة',
    pieces: 'قطع',
    shipmentDescription: 'وصف الشحنة',
    notes: 'ملاحظات',
    trackingNumber: 'Tracking Number',
    orderReference: 'Order Reference',
    returnAddress: 'عنوان المرتجع',
    created: 'Created',
  },
  en: {
    recipientDetails: "Recipient's details",
    phoneNumber: 'Phone Number',
    number1: 'NUMBER 1',
    number2: 'NUMBER 2',
    address: 'Address',
    packagingNotes: 'Packaging Notes',
    packagingWarning: 'Make sure it is not torn and is in good condition without defects.',
    shipmentContents: 'Details',
    shippingNotes: 'Shipping Notes',
    shippingInfo: 'Shipping information',
    allowOpenShipment: 'Is it allowed to open the shipping?',
    paymentMethod: 'payment method',
    paymentStatus: 'Payment status',
    shipmentStatus: 'Shipment status',
    customerSchedule: "Customer's schedule",
    totalPrice: 'Total Price',
    nonReceiptMessage: 'In case of non-receipt:',
    nonReceiptSuffix: 'will be charged.',
    productCount: 'Product Count',
    shippingBarcode: 'Shipping Barcode',
    contactMessage: 'For inquiries and complaints, please contact us.',
    senderName: "Sender's name",
    workNumbers: 'Available work numbers',
    scanToContact: 'Scan to Contact',
    yes: 'yes',
    no: 'no',
    paid: 'paid',
    unpaid: 'unpaid',
    cashOnDelivery: 'Cash on delivery',
    cod: 'COD',
    delivery: 'Delivery',
    codAmount: 'COD Amount',
    nonReceiptCost: 'Non-receipt Cost',
    merchant: 'Merchant',
    deliverTo: 'Deliver to',
    area: 'Area',
    landmark: 'Landmark',
    openShipment: 'Open Shipment',
    pieces: 'Pieces',
    shipmentDescription: 'Shipment Description',
    notes: 'Notes',
    trackingNumber: 'Tracking Number',
    orderReference: 'Order Reference',
    returnAddress: 'Return Address',
    created: 'Created',
  },
};
